// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7th3xnTSI6LBvnBY2vnKSijYdm4IrIEI',
    appId: '1:952538914462:web:b0281465a857aae1b8658f',
    messagingSenderId: '952538914462',
    projectId: 'chat-54332',
    authDomain: 'chat-54332.firebaseapp.com',
    storageBucket: 'chat-54332.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ewaMynk5FGDvLHPfRqq9iGlTf5bAtgA',
    appId: '1:952538914462:android:eff1877eedfe23d0b8658f',
    messagingSenderId: '952538914462',
    projectId: 'chat-54332',
    storageBucket: 'chat-54332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBay4wzy61DfKUZmtyZUycvnv6FuTwJ5r8',
    appId: '1:952538914462:ios:cd5fcec7e211dc82b8658f',
    messagingSenderId: '952538914462',
    projectId: 'chat-54332',
    storageBucket: 'chat-54332.firebasestorage.app',
    iosBundleId: 'com.example.flutterChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBay4wzy61DfKUZmtyZUycvnv6FuTwJ5r8',
    appId: '1:952538914462:ios:cd5fcec7e211dc82b8658f',
    messagingSenderId: '952538914462',
    projectId: 'chat-54332',
    storageBucket: 'chat-54332.firebasestorage.app',
    iosBundleId: 'com.example.flutterChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7th3xnTSI6LBvnBY2vnKSijYdm4IrIEI',
    appId: '1:952538914462:web:4caf5f129b5db6bab8658f',
    messagingSenderId: '952538914462',
    projectId: 'chat-54332',
    authDomain: 'chat-54332.firebaseapp.com',
    storageBucket: 'chat-54332.firebasestorage.app',
  );
}
